
macMapDict = {
'amazon12':'<map id="scaleMap0" name="amazon12_map"><area target="" alt="AMAZON_CONTROL_BACK" title="AMAZON_CONTROL_BACK" href="javascript:advanceExperiment(\'back\')" coords="17,52,27" shape="circle"><area target="" alt="AMAZON_CONTROL_LOGIN" title="AMAZON_CONTROL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1461,129,1626,261" shape="rect"></map>',
'amazon':'<map id="scaleMap0" name="amazon_map"><area target="" alt="AMAZON_TOOL_BACK" title="AMAZON_TOOL_BACK" href="javascript:advanceExperiment(\'back\')" coords="22,50,23" shape="circle"><area target="" alt="AMAZON_TOOL_LOGIN" title="AMAZON_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1463,129,1619,187" shape="rect"></map>',
'expedia12':'<map id="scaleMap0" name="expedia12_map"><area target="" alt="EXPEDIA_CONTROL_BACK" title="EXPEDIA_CONTROL_BACK" href="javascript:advanceExperiment(\'back\')" coords="14,47,27" shape="circle"><area target="" alt="EXPEDIA_CONTROL_LOGIN" title="EXPEDIA_CONTROL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="925,211,1134,126" shape="rect"></map>',
'expedia':'<map id="scaleMap0" name="expedia_map"><area target="" alt="EXPEDIA_TOOL_BACK" title="EXPEDIA_TOOL_BACK" href="javascript:advanceExperiment(\'back\')" coords="12,54,30" shape="circle"><area target="" alt="EXPEDIA_TOOL_LOGIN" title="EXPEDIA_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="825,300,1034,253" shape="rect"><area target="" alt="EXPEDIA_TOOL_LOGIN" title="EXPEDIA_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1127,179,1207,219" shape="rect"></map>',
'netflix12':'<map id="scaleMap0" name="netflix12_map"><area target="" alt="NETFLIX_CONTROL_BACK" title="NETFLIX_CONTROL_BACK" href="javascript:advanceExperiment(\'back\')" coords="10,53,28" shape="circle"><area target="" alt="NETFLIX_CONTROL_LOGIN" title="NETFLIX_CONTROL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1754,136,1845,86" shape="rect"></map>',
'netflix':'<map id="scaleMap0" name="netflix_map"><area target="" alt="NETFLIX_TOOL_BACK" title="NETFLIX_TOOL_BACK" href="javascript:advanceExperiment(\'back\')" coords="19,49,23" shape="circle"><area target="" alt="NETFLIX_TOOL_LOGIN" title="NETFLIX_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1752,220,1847,176" shape="rect"></map>',
'twitter12':'<map id="scaleMap0" name="twitter12_map"><area target="" alt="TWITTER_CONTROL_BACK" title="TWITTER_CONTROL_BACK" href="javascript:advanceExperiment(\'back\')" coords="15,45,23" shape="circle"><area target="" alt="TWITTER_CONTROL_LOGIN" title="TWITTER_CONTROL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1274,290,1366,247" shape="rect"></map>',
'twitter':'<map id="scaleMap0" name="twitter_map"><area target="" alt="TWITTER_TOOL_BACK" title="TWITTER_TOOL_BACK" href="javascript:advanceExperiment(\'back\')" coords="19,51,26" shape="circle"><area target="" alt="TWITTER_TOOL_LOGIN" title="TWITTER_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1309,405,1416,352" shape="rect"><area target="" alt="TWITTER_TOOL_LOGIN" title="TWITTER_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1433,184,1549,227" shape="rect"></map>',
'ups12':'<map id="scaleMap0" name="ups12_map"><area target="" alt="UPS_CONTROL_BACK" title="UPS_CONTROL_BACK" href="javascript:advanceExperiment(\'back\')" coords="15,46,28" shape="circle"><area target="" alt="UPS_CONTROL_LOGIN" title="UPS_CONTROL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="446,113,522,77" shape="rect"></map>',
'ups':'<map id="scaleMap0" name="ups_map"><area target="" alt="UPS_TOOL_BACK" title="UPS_TOOL_BACK" href="javascript:advanceExperiment(\'back\')" coords="15,47,20" shape="circle"><area target="" alt="UPS_TOOL_LOGIN" title="UPS_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="480,198,539,171" shape="rect"></map>',
'yelp12':'<map id="scaleMap0" name="yelp12_map"><area target="" alt="YELP_CONTROL_BACK" title="YELP_CONTROL_BACK" href="javascript:advanceExperiment(\'back\')" coords="15,48,23" shape="circle"><area target="" alt="YELP_CONTROL_LOGIN" title="YELP_CONTROL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1240,153,1310,105" shape="rect"></map>',
'yelp':'<map id="scaleMap0" name="yelp_map"><area target="" alt="YELP_TOOL_BACK" title="YELP_TOOL_BACK" href="javascript:advanceExperiment(\'back\')" coords="18,52,24" shape="circle"><area target="" alt="YELP_TOOL_LOGIN" title="YELP_TOOL_LOGIN" href="javascript:advanceExperiment(\'login\')" coords="1244,236,1310,192" shape="rect"></map>'
};

var dict = {};

dict["US"] = macMapDict;

